# Generated by Django 6.0.3 on 2026-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_followers',
            field=models.BooleanField(default=True),
        ),
    ]
